### PR TITLE
add placeholders 

### PR DESCRIPTION
**Pull request by Saipade**
Usage:
Encoding
cat [ENCODE INPUT] | python3 placeholders.py --encode --config static/placeholder_config.yaml -t [ENCODE OUTPUT]
Decoding
cat [ENCODE OUTPUT] | python3 placeholders.py --decode --config static/placeholder_.yaml -t [DECODE OUTPUT]

Regex patterns and list of placeholders are in the config file

### CODE REVIEW

**Comment by XapaJIaMnu** [comment]
Also, forgot to mention. A point is made that we need to know the number of placeholders in advance so we can prepend them to the spm vocabulary. Could you add that to the configuration file. Eg `num-placeholders: 7` and then something like `--dump-placeholders` in order to know what we should add to the vocabulary-building-step.

**Comment by XapaJIaMnu** [comment]
Sample spm model: http://data.statmt.org/bergamot/models/fren/$lang/$model/vocab.fren.spm

Command used to train it:
```
spm_train --bos_id=-1 --eos_id=0 --unk_id=1 --model_prefix="vocab" --vocab_size=32000 --input=merged.corpus
```

**Comment by XapaJIaMnu** [comment]
Could you also push your test case to the PR as well (however minimum it is, it is still better than nothing)

**Comment by XapaJIaMnu** [comment]
Final request, just add a simple bash script with the encode/decode wrapped on your test example. It doesn't need to check tests, just something for newer users to get started it.

(Or just a README section with a one liner)

**Comment by jelmervdl** [comment]
Faheem was testing this I believe? I'll ask him about approval (once I figure out his github account…)

**Comment by XapaJIaMnu** [comment]
Don't do anything more here, I'm changing this a bit and will open a new one later

**Comment by XapaJIaMnu** [comment]
Superseded by #32

**Pull request closed without merging**
